#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
CF_RELEASE_DIR=${CF_RELEASE_DIR:-$BOSH_RELEASES_DIR/cf-release}

if [[ ! -d $CF_RELEASE_DIR ]]; then
  echo "Cannot find cf-release at $CF_RELEASE_DIR; override with \$CF_RELEASE_DIR variable"
  exit 1
fi

cp manifests/cf-stub.yml manifests/cf-manifest.yml
BOSH_LITE_IP=$(bosh status | grep URL | awk '{print $2}' | sed -e "s/https:\/\///" | sed -e "s/:25555//")
echo $BOSH_LITE_IP
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" manifests/cf-manifest.yml
perl -pi -e "s/10\.244\.0\.254.xip.io/$BOSH_LITE_IP.xip.io/g" manifests/cf-manifest.yml
bosh deployment manifests/cf-manifest.yml
bosh -n diff $BOSH_RELEASES_DIR/cf-release/templates/cf-aws-template.yml.erb
scripts/transform.rb -f manifests/cf-manifest.yml
